networks:
  quizNet:
    external: false

services:
  QuizServiceDBMongo:
    container_name: QuizServiceDBMongo
    image: mongo:latest
    restart: always
    hostname: QuizServiceDBMongo
    ports:
      - "27017:27017"
    networks:
      - quizNet



  QuizServiceAPI:
    container_name: QuizServiceAPI
    build:
      context: ./QuizService
      dockerfile: Dockerfile
    image: quizserviceapi:1
    restart: always
    hostname: QuizServiceAPI
    ports:
      - "8081:8080"
    networks:
      - quizNet
    depends_on:
      - QuizServiceDBMongo
  
  UserServiceAPI:
    container_name: UserServiceAPI
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: userserviceapi:1
    restart: always
    hostname: UserServiceAPI
    ports:
      - "8082:8082"
    environment:
      REDIS_HOST: UserServiceDBRedis
      REDIS_PORT: 6379
      CLASSIC_QUIZ_SERVICE_URL: http://QuizServiceAPI:8080/api/classicQuiz
    networks:
      - quizNet
    depends_on:
      - UserServiceMariadb
  
  UserServiceMariadb:
    container_name: UserServiceMariadb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"   # Host port 3307 maps to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: usersdb
    volumes:
      - usersdb_data:/var/lib/mysql
    networks:
      - quizNet

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - quizNet

  AuthServiceAPI:
    container_name: AuthServiceAPI
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    image: authserviceapi:1
    restart: always
    hostname: AuthServiceAPI
    ports:
      - "8083:8083"
    environment:
      DB_HOST: UserServiceMariadb
      DB_USER: root
      DB_PASSWORD: abc123
      DB_NAME: usersdb
      DB_PORT: 3306
      PORT: 8083
      # Add other environment variables as needed
    networks:
      - quizNet
    depends_on:
      - UserServiceMariadb

volumes:
  usersdb_data:



